src/tweetme/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from .views import home 
from tweets.views import TweetListView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TweetListView.as_view(), name='home'),
    path('tweet/',include('tweets.urls', namespace = 'tweet')),
]

if settings.DEBUG:
	urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/tweets/urls.py
from django.urls import path 
from .views import TweetDetailView , TweetListView , TweetCreateView , TweetUpdateView , TweetDeleteView
from django.views.generic.base import RedirectView
app_name = 'tweets'

urlpatterns = [
    #spath('admin/', admin.site.urls),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('search/', TweetListView.as_view(), name='list'),
    path('new/',TweetCreateView.as_view() , name ='create' ),
    path('<int:pk>/delete/',TweetDeleteView.as_view(), name = 'delete'),
    path('<int:pk>/update/',TweetUpdateView.as_view() , name = 'update'),
    path('',RedirectView.as_view(url='/') )

]

src/tweets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.
class Tweet(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete= models.CASCADE)
	content = models.CharField(max_length=140)
	updated = models.DateTimeField(auto_now= True)
	timestamp = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.content)
	def get_absolute_url(self):
		return reverse('tweet:detail',args=[str(self.id)])

src/tweets/forms.py
from django import forms


from .models import Tweet

class TweetModelForm(forms.ModelForm):
	content = forms.CharField(label ='',widget=forms.Textarea(attrs={'placeholder':'Please type your message'}))
	class Meta:
		model = Tweet
		fields = [
		"content"
		]

	

src/tweetme/views.py
from django.shortcuts import render



def home(request):
	return render(request , "home.html", {})

src/tweets/views.py
from django.shortcuts import render
from .models import Tweet
from django.views.generic import DetailView , ListView , CreateView , UpdateView , DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from .forms import TweetModelForm
# Create your views here.

class TweetDetailView(DetailView):
	model = Tweet
	template_name = "tweets/detail_view.html"

class TweetListView(ListView):
	template_name = "tweets/list_view.html"
	def get_queryset(self):
		qs = Tweet.objects.all()
		query = self.request.GET.get("q",None)
		if query is not None:
			qs = qs.filter(Q(content__icontains = query))
		return qs

	def get_context_data(self, **kwargs):
	    context = super().get_context_data(**kwargs)
	    context['create_form'] = TweetModelForm()
	    context['create_url']= reverse_lazy('tweet:create')
	    return context

class TweetCreateView(CreateView):
	model = Tweet
	form_class = TweetModelForm
	template_name = "tweets/create_view.html"
	def form_valid(self , form):
		form.instance.user = self.request.user
		return super().form_valid(form) 

class TweetUpdateView(UpdateView):
	model = Tweet
	fields = ['content']
	template_name = 'tweets/update_view.html'

class TweetDeleteView(DeleteView):
	model = Tweet
	template_name = 'tweets/delete_confirm.html'
	success_url = reverse_lazy('tweet:list')

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
   <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{%block title%}Tweetme{%endblock title %}</title>
  </head>
  <body>
    <div class="container">
      {% include 'navbar.html' %}
      <hr>
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

   <script src="{% static 'js/bootstrap.min.js' %}" ></script>
  </body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block title %} {{block.super}} | Welcome {% endblock %}





 

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Tweetme</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
     
    </ul>
    {% include 'tweets/search_form.html' %}
  </div>
</nav>

src/tweets/templates/tweets/create_view.html
{% extends 'base.html'%}

{% block content %}
	<h1>New article</h1>
	<form action="" method="post">{% csrf_token %}
		{{form.as_p}}
		<button class="btn btn-success ml-2" type="submit">Send</button>
	</form>	
		
{%endblock %}

src/tweets/templates/tweets/delete_confirm.html
{% extends 'base.html'%}

{% block content %}
	<h1>Delete</h1>
	<form action="" method="post">{% csrf_token %}
		<div class="card">
			<div class="card-header">
				<span class="font-weighted-bold">{{tweet.user}} | {{tweet.updated}}</span>
			</div>
			<div class = "card-body">
				{{tweet.content}}
			</div>
			<div class="card-footer">	
		<input class="btn btn-danger ml-2" type="submit" value="Confirm">
	</div>
</div>
	</form>
	
{% endblock content %}

src/tweets/templates/tweets/detail_view.html
{% extends 'base.html'%}

{% block content %}
	
		<div class="card">
			<div class="card-header">
				<span class="font-weighted-bold">{{tweet.user}} | {{tweet.updated}}</span>
			</div>
		<div class = "card-body">
			{{tweet.content}}
		</div>
			<div class="card-footer text-center text-muted">
				<a href="{% url 'tweet:update' tweet.pk %}">Edit</a> | <a href="{% url 'tweet:delete' tweet.pk %}">Delete</a>
			</div>
		</div>
	
{%endblock content %}

src/tweets/templates/tweets/form.html
<form  method="post" action="{% if action_url %}{{action_url}}{% endif %}">{% csrf_token %}
{{form.as_p}}
<input class= "btn btn-primary" type="submit" value="{{btn_title}}" />
</form>

src/tweets/templates/tweets/list_view.html
{% extends 'base.html' %}


{% block content %}
		
		{% if not request.GET.q %}
			{% include 'tweets/form.html' with form=create_form action_url=create_url btn_title='Tweet' %}
		{% endif %}
		<hr>
		{% for tweet in object_list %}
		<div class="card">
			<div class="card-header">
				<span class="font-weighted-bold">{{tweet.user}} | {{tweet.updated}}</span>
			</div>
		<div class = "card-body">
			{{tweet.content}}
		</div>
			<div class="card-footer text-center text-muted">
				<a href="{% url 'tweet:update' tweet.pk %}">Edit</a> | <a href="{% url 'tweet:delete' tweet.pk %}">Delete</a>
			</div>
				</div>

	{% endfor %}
{%endblock content %}

src/tweets/templates/tweets/search_form.html
<form class="form-inline my-2 my-lg-0" method="GET"  action="{% url 'tweet:list' %}">
	<input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" value="{{request.GET.q}}" />
	<input class="btn btn-outline-success my-2 my-sm-0"  type="submit" value="Search" />
</form>

src/tweets/templates/tweets/update_view.html
{% extends 'base.html' %}

{% block content %}
	<h1>Edit</h1>

	<form method="post">{% csrf_token %}
		{{form.as_p}}
		<button class="btn btn-info ml-2" type="submit">Update</button>
	</form>
{% endblock content %}